### ISSUE TITLE
Location Invalid Issue

### ISSUE THREAD

**Issue by dstrebel** [Azure/azure-dockerdatacenter#2]
When trying to deploy the template through the portal it shows location invalid for all locations. 
![image](https://cloud.githubusercontent.com/assets/3488643/23190760/7c35c994-f85f-11e6-86c4-bfa45f402dfc.png)

**Comment by dwaiba** [comment]
Dear Dave,

There is no default location and you can try deploying in https://preview.portal.azure.com **by switching browsers**... if that does not work cli or powershell deployment would work...  


Also FYI This repo pulls the consolidated tarball for ucp-2.0.1_dtr-2.1.3 only from last known public location @ http://packages.docker.com/caas/ucp-2.0.1_dtr-2.1.3.tar.gz and the latest tags for UCP and DTR are 2.1.0 and  2.2.1, the consolidated public bits are not available except for individual images... Hence manual upgrades are required from the GUI for now.

In a different context: docker4azure is available with OMS @ https://aka.ms/docker4azure where dedicated docker4x azure images are available

**Comment by dwaiba** [comment]
Closing this for now
